apiVersion: v1
kind: ConfigMap
metadata:
  name: oh-my-prompt-config
  namespace: oh-my-prompt
data:
  REDIS_URL: "redis://redis:6379"
  NEXT_PUBLIC_APP_URL: "https://prompt.jiun.dev"
  NODE_ENV: "production"
