apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oh-my-prompt-ingress
  namespace: oh-my-prompt
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - prompt.jiun.dev
      secretName: oh-my-prompt-tls
  rules:
    - host: prompt.jiun.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oh-my-prompt-service
                port:
                  number: 80
