apiVersion: v1
kind: Service
metadata:
  name: oh-my-prompt-service
  namespace: oh-my-prompt
spec:
  selector:
    app: oh-my-prompt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: prompt-db-service
  namespace: oh-my-prompt
spec:
  selector:
    app: prompt-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: oh-my-prompt
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
