const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { execSync, spawn } = require("child_process");
const http = require("http");
const { getConfigDir, ensureDir } = require("./paths");

const SERVE_DIR = path.join(getConfigDir(), "serve");
const COMPOSE_FILE = path.join(SERVE_DIR, "docker-compose.yaml");
const SECRET_FILE = path.join(SERVE_DIR, ".session-secret");

function getServeConfig(config) {
  const image = config.serve?.image || "ghcr.io/jiunbae/oh-my-prompt:latest";
  const port = config.serve?.port || 3000;
  const adminEmail = config.serve?.adminEmail || config.user?.email || "";
  return { image, port, adminEmail };
}

function getSessionSecret() {
  if (fs.existsSync(SECRET_FILE)) {
    return fs.readFileSync(SECRET_FILE, "utf-8").trim();
  }
  const secret = crypto.randomBytes(32).toString("hex");
  ensureDir(SERVE_DIR);
  fs.writeFileSync(SECRET_FILE, secret, { mode: 0o600 });
  return secret;
}

function checkDocker() {
  try {
    execSync("docker info", { stdio: "ignore" });
  } catch {
    throw new Error("Docker is not running. Please start Docker and try again.");
  }
  try {
    execSync("docker compose version", { stdio: "ignore" });
  } catch {
    throw new Error("Docker Compose is not available. Please install Docker Compose.");
  }
}

function generateComposeFile(serveConfig) {
  const secret = getSessionSecret();
  const yaml = `# Auto-generated by omp serve — do not edit
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: prompt
      POSTGRES_PASSWORD: omp-local
      POSTGRES_DB: prompts
    volumes:
      - omp_serve_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prompt -d prompts"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    image: ${serveConfig.image}
    restart: unless-stopped
    ports:
      - "${serveConfig.port}:3000"
    environment:
      DATABASE_URL: postgresql://prompt:omp-local@db:5432/prompts
      REDIS_URL: redis://redis:6379
      SESSION_SECRET: "${secret}"
      OMP_ADMIN_EMAIL: "${serveConfig.adminEmail}"
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  omp_serve_pgdata:
`;
  ensureDir(SERVE_DIR);
  fs.writeFileSync(COMPOSE_FILE, yaml);
  return COMPOSE_FILE;
}

function waitForHealth(port, maxRetries = 30) {
  return new Promise((resolve, reject) => {
    let attempts = 0;
    const check = () => {
      attempts++;
      const req = http.get(`http://localhost:${port}/login`, (res) => {
        if (res.statusCode >= 200 && res.statusCode < 400) {
          resolve();
        } else if (attempts < maxRetries) {
          setTimeout(check, 2000);
        } else {
          reject(new Error(`Server not healthy after ${maxRetries} attempts (status: ${res.statusCode})`));
        }
        res.resume();
      });
      req.on("error", () => {
        if (attempts < maxRetries) {
          setTimeout(check, 2000);
        } else {
          reject(new Error(`Server not reachable after ${maxRetries} attempts`));
        }
      });
      req.setTimeout(3000, () => {
        req.destroy();
        if (attempts < maxRetries) {
          setTimeout(check, 2000);
        } else {
          reject(new Error(`Server timeout after ${maxRetries} attempts`));
        }
      });
    };
    check();
  });
}

function isRunning() {
  if (!fs.existsSync(COMPOSE_FILE)) return false;
  try {
    const out = execSync("docker compose ps --format json", {
      cwd: SERVE_DIR,
      stdio: ["pipe", "pipe", "pipe"],
    }).toString();
    if (!out.trim()) return false;
    const lines = out.trim().split("\n");
    return lines.some((line) => {
      try {
        const svc = JSON.parse(line);
        return svc.Service === "app" && svc.State === "running";
      } catch {
        return false;
      }
    });
  } catch {
    return false;
  }
}

async function startServer(config) {
  checkDocker();
  const serveConfig = getServeConfig(config);

  if (isRunning()) {
    console.log(`Dashboard already running at http://localhost:${serveConfig.port}`);
    return { url: `http://localhost:${serveConfig.port}`, alreadyRunning: true };
  }

  generateComposeFile(serveConfig);

  console.log("Pulling images...");
  try {
    execSync("docker compose pull", { cwd: SERVE_DIR, stdio: "inherit" });
  } catch {
    console.log("Pull failed (cached images will be used if available).");
  }

  console.log("Starting containers...");
  try {
    execSync("docker compose up -d", { cwd: SERVE_DIR, stdio: "inherit" });
  } catch (err) {
    const msg = err.stderr ? err.stderr.toString() : err.message;
    if (msg.includes("port is already allocated")) {
      console.error(`\nPort ${serveConfig.port} is already in use.`);
      console.error(`Change with: omp config set serve.port <port>`);
    } else {
      console.error("\nFailed to start containers:", msg);
    }
    process.exitCode = 1;
    return { url: null, error: "Failed to start" };
  }

  process.stdout.write("Waiting for server to be ready");
  try {
    const origCheck = waitForHealth;
    let dots = setInterval(() => process.stdout.write("."), 1000);
    await waitForHealth(serveConfig.port);
    clearInterval(dots);
    console.log(" ready!");
  } catch (err) {
    console.log(" failed.");
    console.error(err.message);
    console.log("\nCheck logs with: omp serve logs");
    return { url: null, error: err.message };
  }

  const url = `http://localhost:${serveConfig.port}`;
  console.log(`\nDashboard running at ${url}`);
  if (serveConfig.adminEmail) {
    console.log(`Admin email: ${serveConfig.adminEmail}`);
  }
  console.log(`\nTo sync your local data:`);
  console.log(`  omp config set server.url ${url}`);
  console.log(`  # Register at ${url}, then get your token from Settings`);
  console.log(`  omp config set server.token YOUR_TOKEN`);
  console.log(`  omp sync`);

  return { url, alreadyRunning: false };
}

function stopServer() {
  if (!fs.existsSync(COMPOSE_FILE)) {
    console.log("No local server found.");
    return;
  }
  console.log("Stopping containers...");
  execSync("docker compose down", { cwd: SERVE_DIR, stdio: "inherit" });
  console.log("Stopped. Data is preserved in Docker volume (omp_serve_pgdata).");
}

function showStatus() {
  if (!fs.existsSync(COMPOSE_FILE)) {
    console.log("No local server configured. Run 'omp serve' to start.");
    return;
  }
  execSync("docker compose ps", { cwd: SERVE_DIR, stdio: "inherit" });
}

function showLogs(follow) {
  if (!fs.existsSync(COMPOSE_FILE)) {
    console.log("No local server configured. Run 'omp serve' to start.");
    return;
  }
  const args = ["compose", "logs"];
  if (follow) args.push("-f");
  args.push("app");
  const child = spawn("docker", args, { cwd: SERVE_DIR, stdio: "inherit" });
  child.on("error", (err) => {
    console.error("Failed to show logs:", err.message);
  });
  return child;
}

module.exports = {
  startServer,
  stopServer,
  showStatus,
  showLogs,
  isRunning,
  getServeConfig,
  SERVE_DIR,
};
